### ISSUE TITLE
Provides endpoint override for Firestore, Spanner, Pub/Sub and Bigtable

### ISSUE THREAD

**Issue by loicmathieu** [quarkiverse/quarkus-google-cloud-services#98]
Provides endpoint override capabilities for the following service:

- [x] Firestore
- [x] Spanner
- [ ] Pub/Sub
- [ ] BigTable

Storage has already been covered via #92 

The overriding can be done using the following methods:

Client Library | Configure Endpoint
-- | --
Firestore | setHost(hostport)
Spanner | setEmulatorHost(hostport)
Pub/Sub | setChannelProvider with forTarget(hostport) / setEndpoint(endpoint)
Bigtable | setChannelProvider with forTarget(hostport) / setEndpoint(endpoint)

**Comment by PeterUlb** [comment]
I also had a look at PubSub since I do something similar in my project, but this will get a bit more involved if the library should provide some defaults.
What I currently use is my own `PubSubFactory`, which is configurable with a connection type (plaintext or secure) + Endpoint. I think the spring project uses something similar (Autowired PubSubTemplate which has a Publisher and Subscriber Factory).

But to provide any value. many settings must be customizable. like `MaxOutstandingElementCount` and `ExecutorThreadCount`. 
A big painpoint is that the emulator only works with plaintext. 

So IF a Factory shall be provided, the design of all the configuration possibilities is a big question mark. It would allow providing something similar to [this](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/pubsub/GcpPubSubEmulatorAutoConfiguration.java), but would force people to use the factory. 
Not sure if such a factory could keep all configuration options and just override what's needed based on configuration.

On a quick glance I couldn't find how `PubSubTemplate` allows to create a subscriber with e.g. a specific queueSize.

**Comment by loicmathieu** [comment]
Pub/Sub and Bigtable didn't have any global object produced as a CDI beans (as Storage, Firestore and Spanner have), so there is no easy way to provides endpoint override, user needs to do it at their side.

The other now have endpoint override.
